# <span style="color:red"> DATASCI 151 - Practice Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [1]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

In [5]:
# import necessary libraries here
import pandas as pd
import numpy as np

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories.

$\qquad$ ``` ["1941-1967","1968-2003","2004-onwards"] ```

- You must use the `pd.cut` function to recode this variable.

- Print the DataFrame to the screen to check your answers

In [11]:
# your code here
movie_df = pd.read_csv("quiz_data/movies.csv")
new_bins = [1940, 1967, 2003, np.inf]
new_labels = ["1941-1967", "1968-2003", "2004-onwards"]

movie_df["time_period"] = pd.cut(movie_df["year"], 
                                bins = new_bins,
                                right = True,
                                labels = new_labels)

print(movie_df)

                         title   country  runtime(minutes)  year  imdb_score  \
0                   Past Lives  American               106  2023         7.8
1                 Citizen Kane  American               119  1941         8.2
2                      Revenge    France               108  2017         6.4
3                         Okja    Korean               120  2017         7.3
4                      Shutter  Thailand                97  2004         7.0
5        A Tale of Two Sisters    Korean               115  2003         7.1
6                  La Chinoise    France                96  1967         6.9
7   The Umbrellas of Cherbourg    France                91  1964         7.8
8                        House     Japan                88  1977         7.2
9                     Suspiria     Italy                98  1977         7.3
10                 Blue Velvet  American               120  1986         7.7

     time_period
0   2004-onwards
1      1941-1967
2   2004-onwards
3   2004-onwards
4   2004-onwards
5      1968-2003
6      1941-1967
7      1941-1967
8      1968-2003
9      1968-2003
10     1968-2003

<font size = "4">

**Q2** Aggregate and Sort

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Group the data by "country"
    
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score

    - Sort by average IMDB score in **descending order**

- Print the resulting DataFrame to the screen

**Note:** A "single line of code" can continue on to the next line if you use a backslash or wrap the line within a pair of parentheses.

In [ ]:
# your code here
movie_stats = (movie_df.groupby("country").agg(average_runtime = ('runtime(minutes)','mean'), 
                                               maximum_runtime = ('runtime(minutes)','max'),
                                               average_imdb = ('imdb_score','mean'),
                                               min_imdb = ('imdb_score','min')).
                                               sort_values(by = "average_imdb", ascending = False))

<font size = "4">

**Q3** Subsetting data

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Subset the observations for 'country == "France" using ```.query()```

    - Sort the values by year (oldest first)

    - Extract the two oldest movies

In [24]:
# your code here
movie_df.query("country == 'France'").sort_values(by = "year", ascending = True).iloc[:2,:]

,title,country,runtime(minutes),year,imdb_score,time_period
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967

<font size = "4">

**Q4** Aggregate and query

<font size = "3">

- Read in the file "sprint_results.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Do the following in a single line using chaining:

    - Extract the subset with constructorId equal to 51.

    - Aggregate the maximum number of laps and average number of laps for each driver in the subset.

    - Extract the subset of these drivers with maximum # of laps $\geq 20$.

In [28]:
# your code here
sprint_df = pd.read_csv("quiz_data/sprint_results.csv")
sprint_df.query("constructorId == 51").groupby("driverId").agg(max_laps = ('laps','max'),
                                           avg_laps = ('laps', 'mean')).query("max_laps >= 20")

          max_laps   avg_laps
driverId
8               24  20.500000
822             23  22.000000
841             24  19.666667
855             23  11.500000

<font size = "4">

**Q5** Calculate race duration

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Group the data by **both** "raceId" and "constructorId" and calculate the average race duration in minutes for each group.

- Sort the data in descending order and then extract the raceId/constructorId pairs with the 5 slowest average times.

In [36]:
# your code here
race_df = pd.read_csv("quiz_data/results_cleaned.csv")
race_df["race_duration_minutes"] = race_df["milliseconds"] / 60000
grouped = race_df.groupby(["raceId", "constructorId"])
grouped["race_duration_minutes"].mean().sort_values(ascending = False).iloc[:5]

raceId  constructorId
818     129              251.509000
        107              248.783000
847     15               245.466258
        3                245.410900
        5                245.350783
Name: race_duration_minutes, dtype: float64

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv".

- When a driver finishes 1st, 2nd, or 3rd it is known as a "podium finish". Write a function that takes in a Pandas Series and returns the number of entries $\leq 3$.

- Group by "driverId" and then aggregate the following statistics: the average of the "points" column, and the number of podium finishes in the "positionOrder" column - use your custom function for this second statistic.

- Merge the aggregated data back into the original DataFrame.

In [43]:
# your code here
def podium_finish(data):
    index = 0
    for finish in data:
        if finish <= 3:
            index = index + 1
    return index

grouped2 = grouped = race_df.groupby("driverId").agg(avg_points = ('points','mean'),
                                                     podium = ('positionOrder', podium_finish))

final_df = pd.merge(race_df, grouped2, on = "driverId", how = "left")
print(final_df)

       resultId  raceId  driverId  constructorId number  grid position  \
0             1      18         1              1     22     1        1
1             2      18         2              2      3     5        2
2             3      18         3              3      7     7        3
3             4      18         4              4      5    11        4
4             5      18         5              1     23     3        5
...         ...     ...       ...            ...    ...   ...      ...
25655     25661    1086       825            210     20    13       16
25656     25662    1086       848              3     23    17       17
25657     25663    1086       849              3      6    19       18
25658     25664    1086       852            213     22    16       19
25659     25665    1086       822             51     77     8       20

      positionText  positionOrder  points  ...         time milliseconds  \
0                1              1    10.0  ...  1:34:50.616    5690616.0
1                2              2     8.0  ...       +5.478    5696094.0
2                3              3     6.0  ...       +8.163    5698779.0
3                4              4     5.0  ...      +17.181    5707797.0
4                5              5     4.0  ...      +18.014    5708630.0
...            ...            ...     ...  ...          ...          ...
25655           16             16     0.0  ...           \N          NaN
25656           17             17     0.0  ...           \N          NaN
25657           18             18     0.0  ...           \N          NaN
25658           19             19     0.0  ...           \N          NaN
25659           20             20     0.0  ...           \N          NaN

       fastestLap rank fastestLapTime fastestLapSpeed statusId  \
0              39    2       1:27.452         218.300        1
1              41    3       1:27.739         217.586        1
2              41    5       1:28.090         216.719        1
3              58    7       1:28.603         215.464        1
4              43    1       1:27.418         218.385        1
...           ...  ...            ...             ...      ...
25655          37   15       1:23.511         188.856       11
25656          43   12       1:23.047         189.911       11
25657          60    8       1:22.478         191.221       11
25658          58   16       1:23.538         188.795       12
25659          60   19       1:24.002         187.752      131

       race_duration_minutes  avg_points  podium
0                  94.843600   14.313953     188
1                  94.934900    1.407609      13
2                  94.979650    7.740291      57
3                  95.129950    5.790831      98
4                  95.143833    0.937500       4
...                      ...         ...     ...
25655                    NaN    1.330827       1
25656                    NaN    3.921569       2
25657                    NaN    0.134615       0
25658                    NaN    1.228571       0
25659                    NaN    9.244792      67

[25660 rows x 21 columns]